name: Build and push production image

on:
  push:
    branches: [ release-4.7 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # build actual image
    - name: Build controller image
      run: docker build . --file images/openshift-acme-controller/Dockerfile --tag letsencrypt-acme/openshift-acme-controller:0.8.1
    - name: Build exposer image
      run: docker build . --file images/openshift-acme-exposer/Dockerfile --tag letsencrypt-acme/openshift-acme-exposer:0.8.1

    # and push it to dockerHub
    - name: Push docker image
      env:
        docker_server: ${{ secrets.SNAPP_IC_REGISTRY }}
        docker_uid: ${{ secrets.SNAPP_IC_USERNAME }}
        docker_pwd: ${{ secrets.SNAPP_IC_PASSWORD }}
      run: |
        docker login  -u "$docker_uid" -p "$docker_pwd" "$docker_server" && \
        docker push $docker_server/letsencrypt-acme/openshift-acme-controller:0.8.1 && \
        docker push $docker_server/letsencrypt-acme/openshift-acme-exposer:0.8.1
